extends: cheminfo-typescript
parserOptions:
  project:
    - tsconfig.jest.json
    - test/tsconfig.json
    - packages/image-js/tsconfig.json
    - packages/roi/tsconfig.json
rules:
  no-useless-constructor: off
  no-dupe-class-members: off
  'import/no-unresolved': off
  'import/export': off
  no-var: error
  prefer-const: error
  'import/no-extraneous-dependencies': off
