language: node_js
node_js:
  - "0.12"
  - "iojs"
root: false
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
